---

- name: Install the databases used
  apt:
    name:
      - mysql-server
      - mysql-client
      - libmysqlclient-dev
      - python-mysqldb
    state: present
    force: yes

- name: ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes

- name: copy .my.cnf file with root password credentials
  template:
    src: my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600

# Set up MYSQL properly

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: localhost
    password: "{{ root_mysql_password }}"

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host_all: yes
    password: "{{ root_mysql_password }}"

- name: Remove the anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: remove the test database
  mysql_db:
    name: test
    state: absent
