---

# Set up the database

- name: Create database user for the forum
  mysql_user:
    name: "{{ db[domain].forum.user }}"
    password: "{{ db[domain].forum.password }}"
    host: localhost
    state: present
  remote_user: root

- name: Create database for the forum
  mysql_db:
    name: "{{ db[domain].forum.name }}"
    state: present
  remote_user: root

- name: Grant db user privileges
  mysql_user:
    name: "{{ db[domain].forum.user }}"
    priv: "{{ db[domain].forum.name }}.*:ALL"
  remote_user: root

# Download the installer if needed

- name: Ensure download folder exists
  file:
    dest: "{{ ansible_env.HOME }}/downloads/"
    state: directory

- name: Download the phpBB3 installer
  unarchive:
    src: "{{ phpbb_download_url }}"
    dest: "{{ ansible_env.HOME }}/downloads/"
    copy: no
    creates: "{{ ansible_env.HOME }}/downloads/phpBB3"

# Set up document root etc.

- name: Ensure docroot exists
  file:
    dest: "{{ docroot }}"
    state: directory
    mode: 0750

- name: stat 'phpBB3' folder
  stat:
    path: "{{ forum_path }}/"
  register: stat_forum

- name: Move forum to public_html
  command: mv {{ ansible_env.HOME }}/downloads/phpBB3 {{ forum_path }}
  when: not stat_forum.stat.exists

- name: Ensure the apache user is part of the app user group
  user:
    name: www-data
    append: yes
    groups: "{{ item }}"
  with_items: "{{ users }}"
  remote_user: root

- name: Delete install directory
  file:
    path: "{{ forum_path }}/install"
    state: absent

- name: Install correct config file
  template:
    src: config.php.j2
    dest: "{{ forum_path }}/config.php"
    mode: 0740

- name: Set group-write permissions on the required folders
  file:
    path: "{{ forum_path }}/{{ item }}"
    state: directory
    mode: 0770
    recurse: yes
  with_items:
    - cache
    - files
    - store
    - images
    - static
  when: not stat_forum.stat.exists

- name: Ensure X-Forwarded-For header is respected
  blockinfile:
    dest: "{{ forum_path }}/includes/startup.php"
    block: |
      // Fix for reverse proxy
      if(!empty($_SERVER['HTTP_X_FORWARDED_FOR']) && $_SERVER['SERVER_ADDR'] == $_SERVER['REMOTE_ADDR']) {
              $_SERVER['REMOTE_ADDR'] = htmlspecialchars((string) $_SERVER['HTTP_X_FORWARDED_FOR']);
      }
    insertbefore: "// Report all errors, except notices and deprecation messages"

