---

- name: Ensure the log directory exists
  file:
    dest: /var/log/apache2/{{ user }}.{{ env }}
    state: directory
    owner: www-data
    group: www-data
  remote_user: root

- name: Ensure that the needed modules are enabled
  file:
    src: "../mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items:
    - headers.load
    - php5.load
    - php5.conf
    - rewrite.load  # required for the shop
  remote_user: root
  notify:
    - reload apache

- name: Install the Apache config file
  template:
    src: httpd.conf.j2
    dest: "/etc/apache2/sites-available/{{ user }}.{{ env }}.conf"
  remote_user: root
  notify:
    - reload apache

- name: Ensure the site is enabled (symlink)
  file:
    src: "/etc/apache2/sites-available/{{ user }}.{{ env }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ user }}.{{ env }}.conf"
    state: link
  remote_user: root
  notify:
    - reload apache
