<?
echo '<table width="100%" border="0" cellpadding="1" cellspacing="0">';
echo '<tr>';
echo '<td height="25" background="cellpic1.gif" align="center" class="menu1"><b>Menu</b></td>';
echo '</tr>';
echo '<tr>';
echo '<td bgcolor="#ececec" class="menu2">';
echo 'Wachtwoord wijzigen<br>';
echo '<a href="?do=logoff">Uitloggen</a>';
echo '</td>';
echo '</tr>';
echo '</table>';
$sql = 'SELECT * FROM admusers WHERE id = "'.$_SESSION['obuserid'].'"';
$sqlquery = mysql_query($sql);
while($show = mysql_fetch_array($sqlquery)) {
$gebruikersrechten = $show['rechten'];
}
if ($gebruikersrechten == "1") {
echo '<div id="doline"></div>';
echo '<table width="100%" border="0" cellpadding="1" cellspacing="0">';
echo '<tr>';
echo '<td height="25" background="cellpic1.gif" align="center" class="menu1"><b>Beheren</b></td>';
echo '</tr>';
echo '<tr>';
echo '<td bgcolor="#ececec" class="menu2">';
echo '<a href="?edit=start">Start</a><br>';
echo '<a href="?edit=spotlights">Evenement in de spotlights</a>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<div id="doline"></div>';
echo '<table width="100%" border="0" cellpadding="1" cellspacing="0">';
echo '<tr>';
echo '<td height="25" background="cellpic1.gif" align="center" class="menu1"><b>Gebruikers</b></td>';
echo '</tr>';
echo '<tr>';
echo '<td bgcolor="#ececec" class="menu2">';
echo 'Toevoegen<br>';
echo 'Verwijderen';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<div id="doline"></div>';
echo '<table width="100%" border="0" cellpadding="1" cellspacing="0">';
echo '<tr>';
echo '<td height="25" background="cellpic1.gif" align="center" class="menu1"><b>Evenementen</b></td>';
echo '</tr>';
echo '<tr>';
echo '<td bgcolor="#ececec" class="menu2">';
echo '<a href="?edit=evenementen&optie=toevoegen">Toevoegen</a><br>';
echo '<a href="?edit=evenementen&optie=goedkeuren">Goedkeuren</a><br>';
echo '<a href="?edit=evenementen&optie=bewerken">Bewerken</a>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<div id="doline"></div>';
echo '<table width="100%" border="0" cellpadding="1" cellspacing="0">';
echo '<tr>';
echo '<td height="25" background="cellpic1.gif" align="center" class="menu1"><b>Links</b></td>';
echo '</tr>';
echo '<tr>';
echo '<td bgcolor="#ececec" class="menu2">';
echo 'Toevoegen<br>';
echo 'Bewerken';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<div id="doline"></div>';
echo '<table width="100%" border="0" cellpadding="1" cellspacing="0">';
echo '<tr>';
echo '<td height="25" background="cellpic1.gif" align="center" class="menu1"><b>Column</b></td>';
echo '</tr>';
echo '<tr>';
echo '<td bgcolor="#ececec" class="menu2">';
echo 'Toevoegen<br>';
echo 'Bewerken';
echo '</td>';
echo '</tr>';
echo '</table>';
}
?>