---

- name: Ensure docker prerequisites are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python-apt
    state: present

- name: Add Docker's official GPG key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker

- name: Install Docker CE
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - python-pip

- name: Install Docker-Compose
  pip:
    name: docker-compose
    state: present

- name: Ensure the Docker group exists
  group:
    name: docker
    state: present
