---

# Playbook to set up a new server from scratch

- name: Provision the server
  hosts: web
  remote_user: root
  vars:
    admin_email: "info@regex-it.nl"
  roles:
    - base
    - users
    - docker
