---

- name: Ensure backups directory exists
  file:
    path: "{{ backups_dir }}"
    state: directory
    mode: 0700

- name: Ensure backups subdirectories exist
  file:
    path: "{{ backups_dir }}/{{ item }}"
    state: directory
    mode: 0700
  with_items: "{{ db_folders }}"
