---

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: oudebro
      MYSQL_PASSWORD: letmein
      MYSQL_DATABASE: oudebro
    volumes:
      - mysql_data:/var/lib/mysql

  phpbb3:
    build: .
    image: oudebrommers/phpbb3
    ports:
      - "9000:80"
    environment:
      PHPBB3_DB_HOST: db
      PHPBB3_DB_USER: oudebro
      PHPBB3_DB_PASSWORD: letmein
      PHPBB3_DB_NAME: oudebro
      WP_API_KEY: ${WP_API_KEY:-}
    volumes:
      - cache:/var/www/html/phpbb3/cache
      - uploaded_files:/var/www/html/phpbb3/files
      - uploaded_images:/var/www/html/phpbb3/images
    depends_on:
      - db

volumes:
  mysql_data:
  cache:
  uploaded_files:
  uploaded_images:
